ENV: "dev"
DB_SOURCE: "postgresql://root:pasd@localhost:5432/allegro_trade?sslmode=disable"
MIGRATION_URL: "file://db/migration"
HTTP_SERVER_ADDRESS: "0.0.0.0:8080"
GRPC_SERVER_ADDRESS: "0.0.0.0:50051"
TOKEN_SECRET_KEY: "XCoeLDyoTqnqHbGhupYPTaogELbnNa5o"
ACCESS_TOKEN_DURATION: "30m"
REFRESH_TOKEN_DURATION: "36h"
REDIS_ADDRESS: "0.0.0.0:6379"
EMAIL_SENDER_NAME: "email_sender_name"
EMAIL_SENDER_ADDRESS: "email_sender_address"
EMAIL_SENDER_PASSWORD: "email_sender_password"
