DB_DRIVER: "postgres"
DB_SOURCE: "postgresql://root:pasd@localhost:5432/allegro_trade?sslmode=disable"
SERVER_ADDRESS: "0.0.0.0:8080"
TOKEN_SECRET_KEY: "XCoeLDyoTqnqHbGhupYPTaogELbnNa5o"
ACCESS_TOKEN_DURATION: "30m"
REFRESH_TOKEN_DURATION: "36h"
