// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: detail.sql

package db

import (
	"context"
)

const createDetail = `-- name: CreateDetail :one
INSERT INTO details (
  from_trader_id,
  to_trader_id,
  number
) VALUES (
  $1, $2, $3
) RETURNING id, from_trader_id, to_trader_id, number, created_time
`

type CreateDetailParams struct {
	FromTraderID int64 `json:"from_trader_id"`
	ToTraderID   int64 `json:"to_trader_id"`
	Number       int64 `json:"number"`
}

func (q *Queries) CreateDetail(ctx context.Context, arg CreateDetailParams) (Detail, error) {
	row := q.db.QueryRowContext(ctx, createDetail, arg.FromTraderID, arg.ToTraderID, arg.Number)
	var i Detail
	err := row.Scan(
		&i.ID,
		&i.FromTraderID,
		&i.ToTraderID,
		&i.Number,
		&i.CreatedTime,
	)
	return i, err
}

const getDetail = `-- name: GetDetail :one
SELECT id, from_trader_id, to_trader_id, number, created_time FROM details
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDetail(ctx context.Context, id int64) (Detail, error) {
	row := q.db.QueryRowContext(ctx, getDetail, id)
	var i Detail
	err := row.Scan(
		&i.ID,
		&i.FromTraderID,
		&i.ToTraderID,
		&i.Number,
		&i.CreatedTime,
	)
	return i, err
}

const listDetails = `-- name: ListDetails :many
SELECT id, from_trader_id, to_trader_id, number, created_time FROM details
WHERE 
    from_trader_id = $1 OR
    to_trader_id = $2
ORDER BY id
LIMIT $3
OFFSET $4
`

type ListDetailsParams struct {
	FromTraderID int64 `json:"from_trader_id"`
	ToTraderID   int64 `json:"to_trader_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListDetails(ctx context.Context, arg ListDetailsParams) ([]Detail, error) {
	rows, err := q.db.QueryContext(ctx, listDetails,
		arg.FromTraderID,
		arg.ToTraderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Detail
	for rows.Next() {
		var i Detail
		if err := rows.Scan(
			&i.ID,
			&i.FromTraderID,
			&i.ToTraderID,
			&i.Number,
			&i.CreatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
