// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Detail struct {
	ID       int64 `json:"id"`
	TraderID int64 `json:"trader_id"`
	// can be negative or positive
	Number      int64     `json:"number"`
	CreatedTime time.Time `json:"created_time"`
}

type Member struct {
	Membername          string    `json:"membername"`
	PasswordHash        string    `json:"password_hash"`
	NameEntire          string    `json:"name_entire"`
	Email               string    `json:"email"`
	PasswordChangedTime time.Time `json:"password_changed_time"`
	CreatedTime         time.Time `json:"created_time"`
}

type Record struct {
	ID           int64 `json:"id"`
	FromTraderID int64 `json:"from_trader_id"`
	ToTraderID   int64 `json:"to_trader_id"`
	// must be positive
	Number      int64     `json:"number"`
	CreatedTime time.Time `json:"created_time"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Membername   string    `json:"membername"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent  string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiredTime  time.Time `json:"expired_time"`
	CreatedTime  time.Time `json:"created_time"`
}

type Trader struct {
	ID          int64     `json:"id"`
	Holder      string    `json:"holder"`
	Rest        int64     `json:"rest"`
	Symbol      string    `json:"symbol"`
	CreatedTime time.Time `json:"created_time"`
}
