// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTraderRest(ctx context.Context, arg AddTraderRestParams) (Trader, error)
	CreateDetail(ctx context.Context, arg CreateDetailParams) (Detail, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTrader(ctx context.Context, arg CreateTraderParams) (Trader, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteTrader(ctx context.Context, id int64) error
	GetDetail(ctx context.Context, id int64) (Detail, error)
	GetMember(ctx context.Context, membername string) (Member, error)
	GetRecord(ctx context.Context, id int64) (Record, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTrader(ctx context.Context, id int64) (Trader, error)
	GetTraderForUpdate(ctx context.Context, id int64) (Trader, error)
	ListDetails(ctx context.Context, arg ListDetailsParams) ([]Detail, error)
	ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error)
	ListTraders(ctx context.Context, arg ListTradersParams) ([]Trader, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateTrader(ctx context.Context, arg UpdateTraderParams) (Trader, error)
}

var _ Querier = (*Queries)(nil)
