// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddTraderRest(ctx context.Context, arg AddTraderRestParams) (Trader, error)
	CreateDetail(ctx context.Context, arg CreateDetailParams) (Detail, error)
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	CreateTrader(ctx context.Context, arg CreateTraderParams) (Trader, error)
	DeleteTrader(ctx context.Context, id int64) error
	GetDetail(ctx context.Context, id int64) (Detail, error)
	GetRecord(ctx context.Context, id int64) (Record, error)
	GetTrader(ctx context.Context, id int64) (Trader, error)
	GetTraderForUpdate(ctx context.Context, id int64) (Trader, error)
	ListDetails(ctx context.Context, arg ListDetailsParams) ([]Detail, error)
	ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error)
	ListTraders(ctx context.Context, arg ListTradersParams) ([]Trader, error)
	UpdateTrader(ctx context.Context, arg UpdateTraderParams) (Trader, error)
}

var _ Querier = (*Queries)(nil)
