// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: trader.sql

package db

import (
	"context"
)

const addTraderRest = `-- name: AddTraderRest :one
UPDATE traders
SET rest = rest + $1
WHERE id = $2
RETURNING id, holder, rest, symbol, created_time
`

type AddTraderRestParams struct {
	Number int64 `json:"number"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddTraderRest(ctx context.Context, arg AddTraderRestParams) (Trader, error) {
	row := q.db.QueryRowContext(ctx, addTraderRest, arg.Number, arg.ID)
	var i Trader
	err := row.Scan(
		&i.ID,
		&i.Holder,
		&i.Rest,
		&i.Symbol,
		&i.CreatedTime,
	)
	return i, err
}

const createTrader = `-- name: CreateTrader :one
INSERT INTO traders (
  holder,
  rest,
  symbol
) VALUES (
  $1, $2, $3
) RETURNING id, holder, rest, symbol, created_time
`

type CreateTraderParams struct {
	Holder string `json:"holder"`
	Rest   int64  `json:"rest"`
	Symbol string `json:"symbol"`
}

func (q *Queries) CreateTrader(ctx context.Context, arg CreateTraderParams) (Trader, error) {
	row := q.db.QueryRowContext(ctx, createTrader, arg.Holder, arg.Rest, arg.Symbol)
	var i Trader
	err := row.Scan(
		&i.ID,
		&i.Holder,
		&i.Rest,
		&i.Symbol,
		&i.CreatedTime,
	)
	return i, err
}

const deleteTrader = `-- name: DeleteTrader :exec
DELETE FROM traders
WHERE id = $1
`

func (q *Queries) DeleteTrader(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrader, id)
	return err
}

const getTrader = `-- name: GetTrader :one
SELECT id, holder, rest, symbol, created_time FROM traders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTrader(ctx context.Context, id int64) (Trader, error) {
	row := q.db.QueryRowContext(ctx, getTrader, id)
	var i Trader
	err := row.Scan(
		&i.ID,
		&i.Holder,
		&i.Rest,
		&i.Symbol,
		&i.CreatedTime,
	)
	return i, err
}

const getTraderForUpdate = `-- name: GetTraderForUpdate :one
SELECT id, holder, rest, symbol, created_time FROM traders
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetTraderForUpdate(ctx context.Context, id int64) (Trader, error) {
	row := q.db.QueryRowContext(ctx, getTraderForUpdate, id)
	var i Trader
	err := row.Scan(
		&i.ID,
		&i.Holder,
		&i.Rest,
		&i.Symbol,
		&i.CreatedTime,
	)
	return i, err
}

const listTraders = `-- name: ListTraders :many
SELECT id, holder, rest, symbol, created_time FROM traders
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTradersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTraders(ctx context.Context, arg ListTradersParams) ([]Trader, error) {
	rows, err := q.db.QueryContext(ctx, listTraders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trader{}
	for rows.Next() {
		var i Trader
		if err := rows.Scan(
			&i.ID,
			&i.Holder,
			&i.Rest,
			&i.Symbol,
			&i.CreatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrader = `-- name: UpdateTrader :one
UPDATE traders
SET rest = $2
WHERE id = $1
RETURNING id, holder, rest, symbol, created_time
`

type UpdateTraderParams struct {
	ID   int64 `json:"id"`
	Rest int64 `json:"rest"`
}

func (q *Queries) UpdateTrader(ctx context.Context, arg UpdateTraderParams) (Trader, error) {
	row := q.db.QueryRowContext(ctx, updateTrader, arg.ID, arg.Rest)
	var i Trader
	err := row.Scan(
		&i.ID,
		&i.Holder,
		&i.Rest,
		&i.Symbol,
		&i.CreatedTime,
	)
	return i, err
}
